name: Qt CMake Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install Qt
      # https://github.com/jurplel/install-qt-action
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        # For example, if you set dir to ${{ github.workspace }}/example/, your bin folder will be located at $GITHUB_WORKSPACE/example/Qt/5.15.2/{arch}/bin
        dir: '${{ github.workspace }}/Qt_install/'
        # install-deps: 'true'
        # modules: 'qtcharts qtwebengine'
        # archives: 'qtbase qtsvg'
        # cache: 'false'
        # cache-key-prefix: 'install-qt-action'
        # setup-python: 'true'
        # tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        # set-env: 'true'
        # tools-only: 'false'
        # aqtversion: '==3.1.*'
        # py7zrversion: '==0.20.*'
        # extra: '--external 7z'
    
    - name: Generating Build Files
      run: mkdir build; cd build; cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/Qt_install/Qt/6.5.2/gcc_64/lib/cmake" ..

    - name: Building
      run: make
    
    - name: Cleaning
      # maybe deploy artifact later ...
      run: cd ..; echo "Cleaning build directory ..."; rm -r build